# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180409_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='px_per_egg',
            field=models.IntegerField(default=300, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='px_per_tray',
            field=models.IntegerField(default=9000, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 9, 19, 25, 56, 903779, tzinfo=utc)),
        ),
    ]
