# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 20:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180409_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 9, 20, 7, 47, 470313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.TextField(default='egg-510', max_length=300),
        ),
    ]
