# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180409_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_trays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 9, 20, 11, 11, 164853, tzinfo=utc)),
        ),
    ]
