# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180409_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs', models.IntegerField()),
                ('trays', models.CharField(max_length=50)),
                ('damaged', models.IntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 9, 22, 11, 50, 50143, tzinfo=utc)),
        ),
    ]
